import config from '../config/config';

export default {
  user_login: {method: 'post', url: config.baseUrl + 'user/login'},
  school_list: {method: 'post', url: config.baseUrl + 'org/listSchool'},
  school_save: {method: 'post', url: config.baseUrl + 'org/saveSchool'},
  school_update: {method: 'post', url: config.baseUrl + 'org/updateSchool'},
  school_detail: {method: 'post', url: config.baseUrl + 'org/detailSchool'},
  school_detailAccount: {method: 'post', url: config.baseUrl + 'org/detailSchoolAccount'},
  edubureau_list: {method: 'post', url: config.baseUrl + 'org/listEduBureau'},
  edubureau_save: {method: 'post', url: config.baseUrl + 'org/saveEduBureau'},
  edubureau_update: {method: 'post', url: config.baseUrl + 'org/updateEduBureau'},
  edubureau_detail: {method: 'post', url: config.baseUrl + 'org/detailEduBureau'},
  edubureau_detailAccount: {method: 'post', url: config.baseUrl + 'org/detailEduBureauAccount'},
  mechanism_list: {method: 'post', url: config.baseUrl + 'org/listMechanism'},
  mechanism_save: {method: 'post', url: config.baseUrl + 'org/saveMechanism'},
  mechanism_update: {method: 'post', url: config.baseUrl + 'org/updateMechanism'},
  mechanism_detail: {method: 'post', url: config.baseUrl + 'org/detailMechanism'},
  mechanism_detailAccount: {method: 'post', url: config.baseUrl + 'org/detailMechanismAccount'},
  student_list: {method: 'post', url: config.baseUrl + 'student/list'},
  student_save: {method: 'post', url: config.baseUrl + 'student/save'},
  student_update: {method: 'post', url: config.baseUrl + 'student/update'},
  student_detail: {method: 'post', url: config.baseUrl + 'student/detail'},
  class_list: {method: 'post', url: config.baseUrl + 'class/list'},
  user_loginout: {method: 'post', url: config.baseUrl + 'user/loginout'},
  dict_list: {method: 'post', url: config.baseUrl + 'dict/list'},
  teacher_list: {method: 'post', url: config.baseUrl + 'teacher/list'},
  teacher_save: {method: 'post', url: config.baseUrl + 'teacher/save'},
  teacher_update: {method: 'post', url: config.baseUrl + 'teacher/update'},
  teacher_detail: {method: 'post', url: config.baseUrl + 'teacher/detail'},
  import_importStudentParent: {method: 'post', url: config.baseUrl + 'import/importStudentParent'},
  yearterm_list: {method: 'post', url: config.baseUrl + 'yearTerm/list'},
  yearterm_save: {method: 'post', url: config.baseUrl + 'yearTerm/save'},
  yearterm_update: {method: 'post', url: config.baseUrl + 'yearTerm/update'},
  yearterm_detail: {method: 'post', url: config.baseUrl + 'yearTerm/detail'},
  yearterm_currentdetail: {method: 'post', url: config.baseUrl + 'yearTerm/currentDetail'},
  grade_list: {method: 'post', url: config.baseUrl + 'grade/list'},
  option_listGrades: {method: 'post', url: config.baseUrl + 'option/listGrades'},
  grade_save: {method: 'post', url: config.baseUrl + 'grade/save'},
  grade_update: {method: 'post', url: config.baseUrl + 'grade/update'},
  grade_detail: {method: 'post', url: config.baseUrl + 'grade/detail'},
  class_save: {method: 'post', url: config.baseUrl + 'class/save'},
  class_update: {method: 'post', url: config.baseUrl + 'class/update'},
  class_detail: {method: 'post', url: config.baseUrl + 'class/detail'},
  option_listYear: {method: 'post', url: config.baseUrl + 'option/listYear'},
  option_listClassNo: {method: 'post', url: config.baseUrl + 'option/listClassNo'},
  coursecolumn_listFirst: {method: 'post', url: config.baseUrl + 'courseColumn/listFirst'},
  coursecolumn_listSecond: {method: 'post', url: config.baseUrl + 'courseColumn/listSecond'},
  coursecolumn_detail: {method: 'post', url: config.baseUrl + 'courseColumn/detail'},
  coursecolumn_save: {method: 'post', url: config.baseUrl + 'courseColumn/save'},
  coursecolumn_update: {method: 'post', url: config.baseUrl + 'courseColumn/update'},
  courseconfig_list: {method: 'post', url: config.baseUrl + 'courseConfig/list'},
  courseconfig_save: {method: 'post', url: config.baseUrl + 'courseConfig/save'},
  courseconfig_update: {method: 'post', url: config.baseUrl + 'courseConfig/update'},
  zone_listProvince: {method: 'post', url: config.baseUrl + 'zone/listProvince'},
  zone_listCities: {method: 'post', url: config.baseUrl + 'zone/listCities'},
  zone_listCounties: {method: 'post', url: config.baseUrl + 'zone/listCounties'},
  courselibrary_list: {method: 'post', url: config.baseUrl + 'courseLibrary/list'},
  courselibrary_save: {method: 'post', url: config.baseUrl + 'courseLibrary/save'},
  courselibrary_update: {method: 'post', url: config.baseUrl + 'courseLibrary/update'},
  courselibrary_detail: {method: 'post', url: config.baseUrl + 'courseLibrary/detail'},
  course_list: {method: 'post', url: config.baseUrl + 'course/list'},
  course_listschedules: {method: 'post', url: config.baseUrl + 'course/listSchedules'},
  course_saveschoolcourse: {method: 'post', url: config.baseUrl + 'course/saveSchoolCourse'},
  course_savemechanismcourse: {method: 'post', url: config.baseUrl + 'course/saveMechanismCourse'},
  course_updateschoolcourse: {method: 'post', url: config.baseUrl + 'course/updateSchoolCourse'},
  course_updatemechanismcourse: {method: 'post', url: config.baseUrl + 'course/updateMechanismCourse'},
  course_publish: {method: 'post', url: config.baseUrl + 'course/publish'},
  course_unpublish: {method: 'post', url: config.baseUrl + 'course/unpublish'},
  course_batchpublish: {method: 'post', url: config.baseUrl + 'course/batchPublish'},
  course_batchunpublish: {method: 'post', url: config.baseUrl + 'course/batchUnpublish'},
  course_saveoutline: {method: 'post', url: config.baseUrl + 'course/saveOutline'},
  course_getoutline: {method: 'post', url: config.baseUrl + 'course/queryOutline'},
  course_getorders:{method: 'post', url: config.baseUrl + 'courseOrder/list'},
  course_detail:{method: 'post', url: config.baseUrl + 'course/detail'},
  course_updateOrgCourse:{method: 'post', url: config.baseUrl + 'course/updateMechanismCourse'},
  course_updateSchCourse:{method: 'post', url: config.baseUrl + 'course/updateSchoolCourse'}, 
  user_updatePassword:{method: 'post', url: config.baseUrl + 'user/updatePassword'},
  mechanism_register:{method: 'post', url: config.baseUrl + 'org/registerMechanism'},
  mechanism_RegisMechanismCode:{method: 'post', url: config.baseUrl + 'org/sendRegisMechanismCode'},
  mechanism_pass:{method: 'post', url: config.baseUrl + 'org/passMechanism'},
  mechanism_deny:{method: 'post', url: config.baseUrl + 'org/denyMechanism'},
  course_updateTeachers: {method: 'post', url: config.baseUrl + 'course/updateTeachers'},
  notice_list: {method: 'post', url: config.baseUrl + 'notice/list'},
  notice_add: {method: 'post', url: config.baseUrl + 'notice/save'},
  notice_update: {method: 'post', url: config.baseUrl + 'notice/update'},
  notice_del: {method: 'post', url: config.baseUrl + 'notice/del'},
  banner_list: {method: 'post', url: config.baseUrl + 'banner/list'},
  banner_add: {method: 'post', url: config.baseUrl + 'banner/save'},
  banner_update: {method: 'post', url: config.baseUrl + 'banner/update'},
  banner_del: {method: 'post', url: config.baseUrl + 'banner/del'},
  schoolLunch_list: {method: 'post', url: config.baseUrl + 'schoolLunch/list'},
  schoolLunch_add: {method: 'post', url: config.baseUrl + 'schoolLunch/save'},
  schoolLunch_update: {method: 'post', url: config.baseUrl + 'schoolLunch/update'},
  invoice_list: {method: 'post', url: config.baseUrl + 'invoice/listInvoice'},
  invoice_sendAddress: {method: 'post', url: config.baseUrl + 'invoice/sendAddressInvoice'},
  invoice_sendMail: {method: 'post', url: config.baseUrl + 'invoice/sendMailInvoice'},
  mechanism_naturesList: {method: 'post', url: config.baseUrl + 'dict/listMechanismNatures'},
  user_isLogin: {method: 'post', url: config.baseUrl + 'user/isLogin'},
  supplier_list: {method: 'post', url: config.baseUrl + 'supplier/list'},
  supplier_detail: {method: 'post', url: config.baseUrl + 'supplier/detail'},
  supplier_update: {method: 'post', url: config.baseUrl + 'supplier/update'},
  supplier_add: {method: 'post', url: config.baseUrl + 'supplier/save'},
  partner_list: {method: 'post', url: config.baseUrl + 'partner/list'},
  partner_detail: {method: 'post', url: config.baseUrl + 'partner/detail'},
  partner_update: {method: 'post', url: config.baseUrl + 'partner/update'},
  partner_add: {method: 'post', url: config.baseUrl + 'partner/save'},
  courseConfig_list: {method: 'post', url: config.baseUrl + 'courseConfig/list'},
  courseConfig_detail: {method: 'post', url: config.baseUrl + 'courseConfig/detail'},
  courseConfig_update: {method: 'post', url: config.baseUrl + 'courseConfig/update'},
  courseConfig_add: {method: 'post', url: config.baseUrl + 'courseConfig/save'},
  lunchcomment_list:{method: 'post', url: config.baseUrl + 'comment/listLunchComment'},
  user_verification:{method: 'post', url: config.baseUrl + 'user/verification'},
  practiseBase_list:{method: 'post', url: config.baseUrl + 'practiseBase/list'},
  practiseBase_save:{method: 'post', url: config.baseUrl + 'practiseBase/save'},
  practiseBase_detail:{method: 'post', url: config.baseUrl + 'practiseBase/detail'},
  practiseBase_update:{method: 'post', url: config.baseUrl + 'practiseBase/update'},
  practiseBase_list2Option:{method: 'post', url: config.baseUrl + 'practiseBase/list2Option'},
  practiseActivity_batchPublish:{method: 'post', url: config.baseUrl + 'practiseActivity/batchPublish'},
  practiseActivity_batchUnpublish:{method: 'post', url: config.baseUrl + 'practiseActivity/batchUnpublish'},
  practiseActivity_publish:{method: 'post', url: config.baseUrl + 'practiseActivity/publish'},
  practiseActivity_unPublish:{method: 'post', url: config.baseUrl + 'practiseActivity/unpublish'},
  practiseActivity_list:{method: 'post', url: config.baseUrl + 'practiseActivity/list'},
  practiseActivity_detail:{method: 'post', url: config.baseUrl + 'practiseActivity/detail'},
  practiseActivity_save:{method: 'post', url: config.baseUrl + 'practiseActivity/save'},
  practiseActivity_update:{method: 'post', url: config.baseUrl + 'practiseActivity/update'},
  practiseActivity_queryIntro:{method: 'post', url: config.baseUrl + 'practiseActivity/queryIntro'},
  practiseActivity_saveIntro:{method: 'post', url: config.baseUrl + 'practiseActivity/saveIntro'},
  option_listActivityTypes:{method: 'post', url: config.baseUrl + 'option/listActivityTypes'},
  orgWidget_list:{method: 'post', url: config.baseUrl + 'orgWidget/list'},
  orgWidget_post:{method: 'post', url: config.baseUrl + 'orgWidget/save'},
  feedback_list:{method: 'post', url: config.baseUrl + 'feedback/list'},
  comment_detailOrgComment:{method: 'post', url: config.baseUrl + 'comment/detailOrgComment'},
  comment_listOrgComment:{method: 'post', url: config.baseUrl + 'comment/listOrgComment'},
  comment_saveOrgComment:{method: 'post', url: config.baseUrl + 'comment/saveOrgComment'},
};
